a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print ('Só tem espaços? ', a.isspace())
print ('É um número? ', a.isnumeric())
print ('É alfabético? ', a.isnumeric())
print ('É alfanumérico? ', a.isalnum())
print ('Está em maiúscula? ', a.isupper())
print('Esrá capitalizada?', a.istitle())
